### PR TITLE
Basic struct for arena cli update to support volcano

### PR DESCRIPTION
**Pull request by SrinivasChilveri**
This is the initial PR to support volcano in arena cli.

If we want to test timebeing we can install the back end following the belowi links
https://github.com/volcano-sh/volcano
https://volcano.sh/blog/quick-start-volcano/

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/arena/178)

### CODE REVIEW

**Comment by wsxiaozhang** [comment]
@SrinivasChilveri @k82cn  thanks for the PR!  please give us some more time to understand the whole pkg. it's really a BIG one  :)

**Comment by k82cn** [comment]
> it's really a BIG one :)

@SrinivasChilveri , maybe we can separate this PR into few commits, e.g. volcano client, major logic, configuration.

**Comment by SrinivasChilveri** [comment]
@wsxiaozhang , yeah, its little big one.
@k82cn , separated different commits

**Comment by SrinivasChilveri** [comment]
@cheyang  , @denverdino , any comments , updates related to this PR.

**Comment by wsxiaozhang** [comment]
@SrinivasChilveri  thanks for separating it into commits.  I'm going to merge it now. 
Meanwhile could you please add an user guide doc to help users understand how to use a volcanojob?  A new PR for that is welcomed.

**Comment by SrinivasChilveri** [comment]
> @SrinivasChilveri thanks for separating it into commits. I'm going to merge it now.
> Meanwhile could you please add an user guide doc to help users understand how to use a volcanojob? A new PR for that is welcomed.

@wsxiaozhang ,Sure will do the PR for user guide.

**Pull request merged**
