### PR TITLE
Finish arena top node with GPUShare.

### PR DESCRIPTION
**Pull request by Sakuralbj**
Premise: GPU resources on a node are either allocated by card or distributed by memory.

1. arena top node : Show the GPU resource usage of all nodes，If there is a GPUShare node in the entire cluster, the node is displayed as sharable.

2. arena top node -s : Show the GPUMemory resource usage of all GPUShare nodes.

3.arena top node -d: Show details of GPUCount task on a node. Including the name of the task, namespace, and  GPUCount used.

4.arena top node -s -d:Show details of GPUMemory task on a GPUShare node. Including the name of the task, namespace, and  GPUMemory used.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/arena/220)

### CODE REVIEW

**Comment by cheyang** [comment]
@Sakuralbj , Thanks for your contribution. Can you add sample result?

**Comment by Sakuralbj** [comment]
> @Sakuralbj , Thanks for your contribution. Can you add sample result?

**Comment by Sakuralbj** [comment]
Node cn-shanghai.i-uf61h64dz1tmlob9hmtb  is GPUShare, one card ,aliyun.com/gpu-mem=15.
Node cn-shanghai.i-uf61h64dz1tmlob9hmtc is GPUCount, one card, nvidia.com/gpu=1.
Now I create two pods, mymnist1 request nvidia.com/gpu=1,mymnist2 requests aliyun.com/gpu-mem=3.  

pod

This is the result:

arena top node :result . 

arena top node -d:result

arena top node -s:result

arena top node -s -d:result


> @Sakuralbj , Thanks for your contribution. Can you add sample result?

**Comment by Sakuralbj** [comment]
I need to refactor my code.

**Pull request closed without merging**
