### PR TITLE
fix arena submit distribute training command

### PR DESCRIPTION
**Pull request by heluocs**

### CODE REVIEW

**Comment by heluocs** [comment]
@googlebot I signed it!

**Review by xiaozhouX — APPROVED** [review]

**Comment by heluocs** [comment]
@googlebot I fixed it.

**Comment by heluocs** [comment]
@googlebot I fixed it.

**Comment by heluocs** [comment]
@googlebot I fixed it.

**Comment by heluocs** [comment]
@googlebot I fixed it.

**Pull request merged**
