### PR TITLE
feature: add chart version

### PR DESCRIPTION
**Pull request by xiechengsheng**
add chart version info for arena in " arena version" command.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/arena/218)

### CODE REVIEW

**Comment by cheyang** [comment]
@xiechengsheng , Thanks for your contribution! Could you please add sample output of the command?

Take an example as #209 , thanks.

**Comment by xiechengsheng** [comment]
The output:
```sh
$ arena version                        
arena: v0.3.0+dc2076c.dirty
  BuildDate: 2019-07-28T17:27:37Z
  GitCommit: dc2076c3db46b9b7fc8418a15eb5ef1b95f36eda
  GitTreeState: dirty
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
  ChartsVersion: 
    trtserving: 0.0.1
    volcanojob: 0.0.1
    mpijob: 0.17.0
    sparkjob: 0.0.1
    tf-horovod: 0.17.0
    tfjob: 0.21.1
    tfserving: 0.2.0
    training: 0.9.0
```

**Comment by xiechengsheng** [comment]
The updated results:
```sh
# arena version
arena: v0.3.0+ede0c0b
  BuildDate: 2019-07-30T12:42:56Z
  GitCommit: ede0c0b339377b83691f06ba60c7feef73e9e709
  GitTreeState: clean
  GoVersion: go1.11.5
  Compiler: gc
  Platform: linux/amd64

# arena version --verbose
arena: v0.3.0+ede0c0b
  BuildDate: 2019-07-30T12:42:56Z
  GitCommit: ede0c0b339377b83691f06ba60c7feef73e9e709
  GitTreeState: clean
  GoVersion: go1.11.5
  Compiler: gc
  Platform: linux/amd64
  ChartsVersion:
    sparkjob: 0.0.1
    tfjob: 0.21.1
    custom-serving: 0.1.0
    mpijob: 0.17.0
    tf-horovod: 0.17.0
    tfserving: 0.2.0
    training: 0.9.0
    trtserving: 0.0.1
    volcanojob: 0.0.1
```

**Comment by cheyang** [comment]
@xiechengsheng Can you add the info of chart home location, such as `/root/charts` or `/charts`?

**Comment by xiechengsheng** [comment]
Done.
```sh
# arena version --verbose
arena: v0.3.0+5b280ee
  BuildDate: 2019-08-01T01:50:41Z
  GitCommit: 5b280ee490d6c9ae6f73587b19cb6b87369cb746
  GitTreeState: clean
  GoVersion: go1.11.5
  Compiler: gc
  Platform: linux/amd64
  ChartsHome: /charts
  ChartsVersion:
    sparkjob: 0.0.1
    tfjob: 0.21.1
    training: 0.9.0
    trtserving: 0.0.1
    custom-serving: 0.1.0
    mpijob: 0.17.0
    volcanojob: 0.0.1
    tf-horovod: 0.17.0
    tfserving: 0.2.0
```

**Comment by cheyang** [comment]
Thanks, @xiechengsheng

**Pull request merged**
