### PR TITLE
added specification for branch during job submitting

### PR DESCRIPTION
**Pull request by bobmayuze**
added specification for branch during job submitting

### CODE REVIEW

**Comment by cheyang** [comment]
Thank you for contributing! Could you also update the Chinese version: https://github.com/kubeflow/arena/blob/master/docs/userguide_cn/1-tfjob-standalone.md ?

**Comment by bobmayuze** [comment]
@googlebot I signed it!

**Comment by bobmayuze** [comment]
> Thank you for contributing! Could you also update the Chinese version: https://github.com/kubeflow/arena/blob/master/docs/userguide_cn/1-tfjob-standalone.md ?

Sure, on it

**Pull request merged**
