### PR TITLE
update git-sync to version v3.1.1 to fix the git-sync issues-91

### PR DESCRIPTION
**Pull request by Chaos-Ju**
Fix ERROR: can't create .netrc file: error setting up git credentials exit status 255: error: could not lock config file //.gitconfig: Permission denied
Link issue: https://github.com/kubernetes/git-sync/issues/91
Link issue: https://github.com/kubeflow/arena/issues/134
please sync  aliyun  git-sync images   to lastest

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/arena/135)

### CODE REVIEW

**Comment by cheyang** [comment]
Sure, thanks a lot for fixing it. Please sign CLA to create PR.

**Comment by Chaos-Ju** [comment]
I signed it!

**Comment by cheyang** [comment]
@Chaos-Ju Looks like your email "chaosju@163.com" is successfully registered. But the email address you commit is not "chaosju@163.com".

**Comment by Chaos-Ju** [comment]
> @Chaos-Ju Looks like your email "[chaosju@163.com](mailto:chaosju@163.com)" is successfully registered. But the email address you commit is not "[chaosju@163.com](mailto:chaosju@163.com)".

Thanks, I found that its my commany email.

**Comment by cheyang** [comment]
Please commit with the email address "chaosju@163.com". Thanks.

**Pull request closed without merging**
