### PR TITLE
fix get gpu metric error & typo error of "gpu exporter"

### PR DESCRIPTION
**Pull request by soolaugust**
update "expoter" to "exporter"

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/arena/110)

### CODE REVIEW

**Comment by soolaugust** [comment]
@xiaozhouX 

Please help to check this changed is appropriate or not. local test is okay for me.

/assign @xiaozhouX

**Comment by xiaozhouX** [comment]
Thanks for your contribution !

**Comment by soolaugust** [comment]
@wsxiaozhang Please help to check this PR. thanks :)

**Comment by cheyang** [comment]
Thank you for PR to our project! Since we are freezing master branch, can you please close this PR and  submit PR to branch release-v0.2.0! Thanks again!

**Comment by soolaugust** [comment]
okay, I will

**Pull request closed without merging**
