### PR TITLE
Add GPU memory information in arena serving.

### PR DESCRIPTION
**Pull request by Sakuralbj**
Signed-off-by: 630445639 <630445639@qq.com>

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/arena/192)

### CODE REVIEW

**Comment by Sakuralbj** [comment]
> I signed it

**Comment by wsxiaozhang** [comment]
@Sakuralbj these two resource aliyun.com/gpu-mem and  nvidia.com/gpu should not be used at the same time. suggest you to add more logic to check and validate such mis-usage case. thanks.

**Comment by Sakuralbj** [comment]
> @Sakuralbj these two resource aliyun.com/gpu-mem and nvidia.com/gpu should not be used at the same time. suggest you to add more logic to check and validate such mis-usage case. thanks.
I will do it quickly.Thank you.

**Comment by Sakuralbj** [comment]
@cheyang I have done it.

**Pull request closed without merging**
