### PR TITLE
add cpu and mem info in node side

### PR DESCRIPTION
**Pull request by xiechengsheng**
1. this PR adds cpu and mem info in node side.
2. need further discussion about some details: the sum of `kubectl top pod` and `kubectl top node` are not same.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/arena/199)

### CODE REVIEW

**Comment by xieydd** [comment]
Is it necessary to add cpu and memory information like `kubectl top`?

**Comment by xiechengsheng** [comment]
> Is it necessary to add cpu and memory information like `kubectl top`?

For cluster without gpu, it might be helpful?

**Comment by wsxiaozhang** [comment]
@xiechengsheng could please fix the conflicts first?

**Comment by xiechengsheng** [comment]
ok, still need some discussions

**Pull request closed without merging**
