### PR TITLE
init support for estimator mode

### LINKED ISSUE #6: support for distributed tensorflow estimator
Aliyun guru, can you please kindly support run distributed tensorflow estimator, typical usage can be found here [estimator train and evaluate](https://www.tensorflow.org/api_docs/python/tf/estimator/train_and_evaluate)

Key difference from raw API is that estimator must have chief node(worker 0), and suggested to have evaluator node.

In our practice, we have ps, worker, chief and evaluator.

Thanks advance.

### PR DESCRIPTION
**Pull request by cheyang**
1. Init estimator support (chief and evaluator) , for submitting job and get chief pod

2. support tensorboard for estimator, especially when the event log is put in PVC

3. update document for estimator

Fix #6 

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/arena/60)

### CODE REVIEW

**Comment by wsxiaozhang** [comment]
The 'ChiefCount' in submitTFJobArgs seems not necessary. Using 'useChief' is able to decide the number of chief node already.

**Comment by cheyang** [comment]
> The 'ChiefCount' in submitTFJobArgs seems not necessary. Using 'useChief' is able to decide the number of chief node already.

Thank you for review. Updated according to your suggestions..

**Comment by wsxiaozhang** [comment]
got you

/lgtm now

**Pull request merged**
